### ISSUE TITLE
The "one-liner"

### ISSUE THREAD

**Issue by jrmgx** [Augment/Augment.github.io#4]
> context: I'm going to give general feedback about the documentation,
> these are my opinions as an external developer, it is mainly based on my experience with other public SDK (ie: facebook, algolia, branch and so on)
> This is not absolute truth and I post this as issues so we can talk about it

We should have a "one-liner" or similar that a developer can use in his/her existing app and
get something working quickly, then they will be willing to test more: I did a proposal of what it could look like in my PR

**Comment by buranmert** [comment]
I disagree with one-liner approach.

1. One-liner doesn't give control to you over the process where we have a quite long chain of steps which has multiple data tasks->one potential download task->adding model to AR
2. We can provide one-liner and real functions as well. But if we provide multiple ways of achieving the same result, that will be bad design.

Already, current SDK is demanding only 1-2 extra functions calls to use AR in your app. I don't think it is too much.

**Comment by jrmgx** [comment]
I agree that you disagree, so let me explain more the goal of the one-liner.
The idea is only that the developer will copy/past this code into his/her app so he/she will have something working quickly.

It has to be limited by design, 
so when the developer wants to do more than only testing that "it can work"
he/she has to go through the real SDK and documentation.

The on-liner won't allow to do much/anything and should not be a way to use the SDK.
I reckon that is duplicate code in a way, but it is here to seduce the final developer.

Current SDK is not only demanding only 1-2 extra functions calls, 
as an external developer I found it quite overwhelming to implement,
a one-liner will give quick reward to the developer and should help him/her to go further.

**Comment by buranmert** [comment]
It can be easier to discuss on the code design if you can suggest some example code.
Because personally I don't like the fact that we need to connect `AugmentPlayer` to `AGTView` by ourselves but even one-liners can't solve that problem. So I didn't really get what that one-liner is/can be

**Comment by jrmgx** [comment]
I understand that a one-liner is too complex, I remove that suggestion and close this issue.
