### ISSUE TITLE
Contact for developer

### ISSUE THREAD

**Issue by jrmgx** [Augment/Augment.github.io#7]
> context: I'm going to give general feedback about the documentation,
> these are my opinions as an external developer, it is mainly based on my experience with other public SDK (ie: facebook, algolia, branch and so on)
> This is not absolute truth and I post this as issues so we can talk about it

We must tell the developer how to contact us, for bugs and for help.
Do we create a specific channel for this?

**Comment by buranmert** [comment]
Example project has a public GitHub repo, no? we can encourage them to create GitHub issues

**Comment by jrmgx** [comment]
Github issues can be handy for issues about the example projet itself, but what about issue on the SDK?

**Comment by buranmert** [comment]
Example project is nothing but a way of using SDK, basically example project is the face of SDK to the outer world. I think they can create issues here about SDK too

**Comment by jrmgx** [comment]
Sounds good to me :) Let it be the way to gather feedback about the sdk
It needs to be added in the documentation then.
