### ISSUE TITLE
Caching mechanism

### ISSUE THREAD

**Issue by jrmgx** [Augment/Augment.github.io#9]
> context: I'm going to give general feedback about the documentation,
> these are my opinions as an external developer, it is mainly based on my experience with other public SDK (ie: facebook, algolia, branch and so on)
> This is not absolute truth and I post this as issues so we can talk about it

Accessing the caching mechanism should be a very advanced feature, and may not even be in
this documentation (it could be in the full API doc)

**Comment by buranmert** [comment]
Can you please explain a bit more what you mean by caching mechanism? @jrmgx

**Comment by jrmgx** [comment]
that part

```objc
- (void)loadDummyModel {
    AGTProduct *cachedProduct = [self.augmentSDK.productsDataController productForIdentifier:DummyProductIdentifier];
    if (cachedProduct == [AGTProduct unfoundProduct]) {
        NSLog(@"Cached product queried before and there is no model 3D in Augment database!");
    }
    else if (cachedProduct != nil) {
        [self addProductToAugmentPlayer:cachedProduct];
    }
    else {
        [self queryAndAddProductToAugmentPlayerWithIdentifier:DummyProductIdentifier];
    }
}
```

**Comment by buranmert** [comment]
Yes, you are right.
At first, we had `unfoundProduct` scenario, now we don't have that anymore actually.
So this part became trivial. We can/should remove that.
Created an [Aha issue](https://augment.aha.io/features/IOS-99) for myself

**Comment by jrmgx** [comment]
Great, I'll close that issue then.
